### ISSUE TITLE
Error type information is lost when read from errorStream

### ISSUE THREAD

**Issue by ClemannD** [lsqlabs/rxjs-uploader#18]
For example, when a disallowed filetype is uploaded, a `DisallowedContentTypeError` is nexted onto the _errorSubject. When subscribing to the errorStream, the type of the error is `Error`.

It should keep the type information, to allow showing specific error messages to the end user based on the type of error.

**Comment by RobertCMusk** [comment]
Fixed in:
https://github.com/lsqlabs/rxjs-uploader/pull/20
and
https://github.com/lsqlabs/rxjs-uploader/pull/26
