### ISSUE TITLE
errorStream should give the name of the file that the user attempted to upload

### ISSUE THREAD

**Issue by ClemannD** [lsqlabs/rxjs-uploader#19]
Right now there is no way to get the name of the file the user attempted to upload from the error stream.

Potential solution is add  `fileName` as a class field to `FileUploadError`, and set that when nexting `_errorSubject`

**Comment by dmayerdesign** [comment]
The reason you need the `fileName` is to create your own error message, correct? Should we just make it so you can customize your error message at the config level? e.g.
```ts
const uploader = new Uploader({
    // ...
    disallowedContentTypeErrorMessage: (fileUpload) =>
        `${fileUpload.name} was the wrong type`
})
```

**Comment by ClemannD** [comment]
Yes that could work

**Comment by ClemannD** [comment]
https://github.com/lsqlabs/rxjs-uploader/pull/20
